### ISSUE TITLE
[v1.0.3] Error: variable 'lym' referenced before assignment

### ISSUE THREAD

**Issue by agarcia-ruiz** [radiomicsgroup/neuro-app-issues#11]
**Describe the bug**
Error when classifying, after CNN.

**Desktop (please complete the following information):**
 - OS: Windows?
 - Version 1.0.3

**Additional context**
Log:

> 2022-06-27 08:19:56.190574: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-27 08:19:56.190629: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
__main__                       -- INFO     : --------------------Starting event logging--------------------
__main__                       -- INFO     : Start Neuro Version 1.0.3
app.inout.dicom_convert        -- INFO     : dcm2niix dicom conversion
app.inout.dicom_convert        -- INFO     : sitk nii to nrrd conversion
app.processing.preprocess_DSC  -- INFO     : correcting DSC
app.inout.dicom_convert        -- INFO     : dcm2niix dicom conversion
app.inout.dicom_convert        -- INFO     : sitk nii to nrrd conversion
app.processing.preprocess      -- INFO     : correcting T1C
app.processing.reg_imgs        -- INFO     : Registering T1C
app.segmentation.segment_EM    -- INFO     : Segmenting hemispheres
app.segmentation.segment_T1    -- INFO     : Combining Hems and Brain masks
app.inout.dicom_convert        -- INFO     : sitk nii to nrrd conversion
app.segmentation.segment_WM    -- INFO     : Segmenting WM
app.processing.dsc_curves      -- INFO     : DSC curve processing
app.processing.dsc_curves      -- INFO     : Extracting DSC normalization params
app.processing.dsc_curves      -- INFO     : Normalizing DSC curves
app.class_launcher             -- INFO     : Launching classifier
2022-06-27 08:33:02.109893: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2022-06-27 08:33:02.109948: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)
2022-06-27 08:33:02.109975: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (43ae21d72339): /proc/driver/nvidia/version does not exist
2022-06-27 08:33:02.110352: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-06-27 08:33:02.347658: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)
2022-06-27 08:33:02.348082: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 2208005000 Hz
app.class_launcher             -- WARNING  : Only 4 % of high confident voxels. Proceed with caution!
Traceback (most recent call last):
  File "/program/neuro-app/run.py", line 272, in <module>
    main(p_dsc, p_t1, p_output, p_model1, p_model2, th_lym, th_met, p_lesion, p_wm, rerunMask, noReg, noMoCo, logfile)
  File "/program/neuro-app/run.py", line 140, in main
    res = class_launcher.data_class_task(p_curves, p_output, p_model1, p_model2, p_lesion,threshold_lym, threshold_met, p_printim, printout=True, p_print=p_result)
  File "/program/neuro-app/app/class_launcher.py", line 97, in data_class_task
    if not lym:
UnboundLocalError: local variable 'lym' referenced before assignment

**Comment by agarcia-ruiz** [comment]
fixed by neuro-app@[8f5a5bd](https://github.com/radiomicsvhio/neuro-app/commit/8f5a5bdb59561fa17a378f7377d9cbc7cbe1aa45)
